USE Sollo
GO

INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1102','Compra para comercialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1111','Compra para industrialização de mercadoria recebida anteriormente em consignação industrial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1113','Compra para comercialização, de mercadoria recebida anteriormente em consignação mercantil')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1116','Compra para industrialização originada de encomenda para recebimento futuro')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1117','Compra para comercialização originada de encomenda para recebimento futuro')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1118','Compra de mercadoria para comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1120','Compra para industrialização, em venda à ordem, já recebida do vendedor remetente')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1121','Compra para comercialização, em venda à ordem, já recebida do vendedor remetente')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1122','Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1124','Industrialização efetuada por outra empresa')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1125','Industrialização efetuada por outra empresa quando a mercadoria remetida para utilização no processo de industrialização não transitou pelo estabelecimento adquirente da mercadoria')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1126','Compra para utilização na prestação de serviço')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1151','Transferência para industrialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1152','Transferência para comercialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1153','Transferência de energia elétrica para distribuição')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1154','Transferência para utilização na prestação de serviço')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1201','Devolução de venda de produção do estabelecimento')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1202','Devolução de venda de mercadoria adquirida ou recebida de terceiros')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1203','Devolução de venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1204','Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1205','Anulação de valor relativo à prestação de serviço de comunicação')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1206','Anulação de valor relativo à prestação de serviço de transporte')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1207','Anulação de valor relativo à venda de energia elétrica')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1208','Devolução de produção do estabelecimento, remetida em transferência')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1209','Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1251','Compra de energia elétrica para distribuição ou comercialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1252','Compra de energia elétrica por estabelecimento industrial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1253','Compra de energia elétrica por estabelecimento comercial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1254','Compra de energia elétrica por estabelecimento prestador de serviço de transporte')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1255','Compra de energia elétrica por estabelecimento prestador de serviço de comunicação')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1256','Compra de energia elétrica por estabelecimento de produtor rural')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1257','Compra de energia elétrica para consumo por demanda contratada')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1301','Aquisição de serviço de comunicação para execução de serviço da mesma natureza')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1302','Aquisição de serviço de comunicação por estabelecimento industrial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1303','Aquisição de serviço de comunicação por estabelecimento comercial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1304','Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1305','Aquisição de serviço de comunicação por estabelecimento de geradora ou de distribuidora de energia elétrica')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1306','Aquisição de serviço de comunicação por estabelecimento de produtor rural')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1351','Aquisição de serviço de transporte para execução de serviço da mesma natureza')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1352','Aquisição de serviço de transporte por estabelecimento industrial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1353','Aquisição de serviço de transporte por estabelecimento comercial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1354','Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1355','Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1356','Aquisição de serviço de transporte por estabelecimento de produtor rural')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1401','Compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1403','Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1406','Compra de bem para o ativo imobilizado cuja mercadoria está sujeita ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1407','Compra de mercadoria para uso ou consumo cuja mercadoria está sujeita ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1408','Transferência para industrialização em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1409','Transferência para comercialização em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1410','Devolução de venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1411','Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1414','Retorno de produção do estabelecimento, remetida para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1415','Retorno de mercadoria adquirida ou recebida de terceiros, remetida para venda fora do estabelecimento em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1451','Retorno de animal do estabelecimento produtor')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1452','Retorno de insumo não utilizado na produção')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1501','Entrada de mercadoria recebida com fim específico de exportação')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1503','Entrada decorrente de devolução de produto remetido com fim específico de exportação, de produção do estabelecimento')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1504','Entrada decorrente de devolução de mercadoria remetida com fim específico de exportação, adquirida ou recebida de terceiros')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1551','Compra de bem para o ativo imobilizado')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1552','Transferência de bem do ativo imobilizado')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1553','Devolução de venda de bem do ativo imobilizado')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1554','Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1555','Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1556','Compra de material para uso ou consumo')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1557','Transferência de material para uso ou consumo')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1601','Recebimento, por transferência, de crédito de ICMS')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1602','Recebimento, por transferência, de saldo credor de ICMS de outro estabelecimento da mesma empresa, para compensação de saldo devedor de ICMS')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1603','Ressarcimento de ICMS retido por substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1604','Lançamento do crédito relativo à compra de bem para o ativo imobilizado')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1605','Recebimento, por transferência, de saldo devedor de ICMS de outro estabelecimento da mesma empresa')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1650','ENTRADAS DE COMBUSTÍVEIS, DERIVADOS OU NÃO DE PETRÓLEO E LUBRIFICANTES')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1651','Compra de combustível ou lubrificante para industrialização subseqüente')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1652','Compra de combustível ou lubrificante para comercialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1653','Compra de combustível ou lubrificante por consumidor ou usuário final')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1658','Transferência de combustível e lubrificante para industrialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1659','Transferência de combustível e lubrificante para comercialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1660','Devolução de venda de combustível ou lubrificante destinado à industrialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1661','Devolução de venda de combustível ou lubrificante destinado à comercialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1662','Devolução de venda de combustível ou lubrificante destinado a consumidor ou usuário final')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1663','Entrada de combustível ou lubrificante para armazenagem')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1664','Retorno de combustível ou lubrificante remetido para armazenagem')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1901','Entrada para industrialização por encomenda')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1902','Retorno de mercadoria remetida para industrialização por encomenda')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1903','Entrada de mercadoria remetida para industrialização e não aplicada no referido processo')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1904','Retorno de remessa para venda fora do estabelecimento')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1905','Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1906','Retorno de mercadoria remetida para depósito fechado ou armazém geral')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1907','Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1908','Entrada de bem por conta de contrato de comodato')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1909','Retorno de bem remetido por conta de contrato de comodato')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1910','Entrada de bonificação, doação ou brinde')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1911','Entrada de amostra grátis')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1912','Entrada de mercadoria ou bem recebido para demonstração')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1913','Retorno de mercadoria ou bem remetido para demonstração')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1914','Retorno de mercadoria ou bem remetido para exposição ou feira')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1915','Entrada de mercadoria ou bem recebido para conserto ou reparo')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1916','Retorno de mercadoria ou bem remetido para conserto ou reparo')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1917','Entrada de mercadoria recebida em consignação mercantil ou industrial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1918','Devolução de mercadoria remetida em consignação mercantil ou industrial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1919','Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignação mercantil ou industrial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1920','Entrada de vasilhame ou sacaria')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1921','Retorno de vasilhame ou sacaria')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1922','Lançamento efetuado a título de simples faturamento decorrente de compra para recebimento futuro')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1923','Entrada de mercadoria recebida do vendedor remetente, em venda à ordem')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1924','Entrada para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1925','Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1926','Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1931','Lançamento efetuado pelo tomador do serviço de transporte quando a responsabilidade de retenção do imposto for atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na Unidade da Federação onde iniciado o serviço')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1932','Aquisição de serviço de transporte iniciado em Unidade da Federação diversa daquela onde inscrito o prestador')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1933','Aquisição de serviço tributado pelo ISSQN')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('1949','Outra entrada de mercadoria ou prestação de serviço não especificada')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2101','Compra para industrialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2102','Compra para comercialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2111','Compra para industrialização de mercadoria recebida anteriormente em consignação industrial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2113','Compra para comercialização, de mercadoria recebida anteriormente em consignação mercantil')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2116','Compra para industrialização originada de encomenda para recebimento futuro')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2117','Compra para comercialização originada de encomenda para recebimento futuro')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2118','Compra de mercadoria para comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2120','Compra para industrialização, em venda à ordem, já recebida do vendedor remetente')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2121','Compra para comercialização, em venda à ordem, já recebida do vendedor remetente')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2122','Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2124','Industrialização efetuada por outra empresa')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2125','Industrialização efetuada por outra empresa quando a mercadoria remetida para utilização no processo de industrialização não transitou pelo estabelecimento adquirente da mercadoria')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2126','Compra para utilização na prestação de serviço')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2151','Transferência para industrialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2152','Transferência para comercialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2153','Transferência de energia elétrica para distribuição')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2154','Transferência para utilização na prestação de serviço')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2201','Devolução de venda de produção do estabelecimento')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2202','Devolução de venda de mercadoria adquirida ou recebida de terceiros')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2203','Devolução de venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2204','Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2205','Anulação de valor relativo à prestação de serviço de comunicação')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2206','Anulação de valor relativo à prestação de serviço de transporte')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2207','Anulação de valor relativo à venda de energia elétrica')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2208','Devolução de produção do estabelecimento, remetida em transferência')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2209','Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2251','Compra de energia elétrica para distribuição ou comercialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2252','Compra de energia elétrica por estabelecimento industrial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2253','Compra de energia elétrica por estabelecimento comercial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2254','Compra de energia elétrica por estabelecimento prestador de serviço de transporte')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2255','Compra de energia elétrica por estabelecimento prestador de serviço de comunicação')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2256','Compra de energia elétrica por estabelecimento de produtor rural')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2257','Compra de energia elétrica para consumo por demanda contratada')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2301','Aquisição de serviço de comunicação para execução de serviço da mesma natureza')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2302','Aquisição de serviço de comunicação por estabelecimento industrial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2303','Aquisição de serviço de comunicação por estabelecimento comercial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2304','Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2305','Aquisição de serviço de comunicação por estabelecimento de geradora ou de distribuidora de energia elétrica')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2306','Aquisição de serviço de comunicação por estabelecimento de produtor rural')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2351','Aquisição de serviço de transporte para execução de serviço da mesma natureza')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2352','Aquisição de serviço de transporte por estabelecimento industrial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2353','Aquisição de serviço de transporte por estabelecimento comercial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2354','Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2355','Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2356','Aquisição de serviço de transporte por estabelecimento de produtor rural')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2401','Compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2403','Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2406','Compra de bem para o ativo imobilizado cuja mercadoria está sujeita ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2407','Compra de mercadoria para uso ou consumo cuja mercadoria está sujeita ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2408','Transferência para industrialização em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2409','Transferência para comercialização em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2410','Devolução de venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2411','Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2414','Retorno de produção do estabelecimento, remetida para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2415','Retorno de mercadoria adquirida ou recebida de terceiros, remetida para venda fora do estabelecimento em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2501','Entrada de mercadoria recebida com fim específico de exportação')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2503','Entrada decorrente de devolução de produto remetido com fim específico de exportação, de produção do estabelecimento')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2504','Entrada decorrente de devolução de mercadoria remetida com fim específico de exportação, adquirida ou recebida de terceiros')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2551','Compra de bem para o ativo imobilizado')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2552','Transferência de bem do ativo imobilizado')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2553','Devolução de venda de bem do ativo imobilizado')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2554','Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2555','Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2556','Compra de material para uso ou consumo')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2557','Transferência de material para uso ou consumo')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2603','Ressarcimento de ICMS retido por substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2651','ENTRADAS DE COMBUSTÍVEIS, DERIVADOS OU NÃO DE PETRÓLEO E LUBRIFICANTES')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2652','Compra de combustível ou lubrificante para comercialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2653','Compra de combustível ou lubrificante por consumidor ou usuário final')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2658','Transferência de combustível e lubrificante para industrialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2659','Transferência de combustível e lubrificante para comercialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2660','Devolução de venda de combustível ou lubrificante destinado à industrialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2661','Devolução de venda de combustível ou lubrificante destinado à comercialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2662','Devolução de venda de combustível ou lubrificante destinado a consumidor ou usuário final')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2663','Entrada de combustível ou lubrificante para armazenagem')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2664','Retorno de combustível ou lubrificante remetido para armazenagem')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2901','Entrada para industrialização por encomenda')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2902','Retorno de mercadoria remetida para industrialização por encomenda')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2903','Entrada de mercadoria remetida para industrialização e não aplicada no referido processo')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2904','Retorno de remessa para venda fora do estabelecimento')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2905','Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2906','Retorno de mercadoria remetida para depósito fechado ou armazém geral')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2907','Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2908','Entrada de bem por conta de contrato de comodato')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2909','Retorno de bem remetido por conta de contrato de comodato')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2910','Entrada de bonificação, doação ou brinde')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2911','Entrada de amostra grátis')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2912','Entrada de mercadoria ou bem recebido para demonstração')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2913','Retorno de mercadoria ou bem remetido para demonstração')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2914','Retorno de mercadoria ou bem remetido para exposição ou feira')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2915','Entrada de mercadoria ou bem recebido para conserto ou reparo')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2916','Retorno de mercadoria ou bem remetido para conserto ou reparo')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2917','Entrada de mercadoria recebida em consignação mercantil ou industrial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2918','Devolução de mercadoria remetida em consignação mercantil ou industrial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2919','Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignação mercantil ou industrial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2920','Entrada de vasilhame ou sacaria')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2921','Retorno de vasilhame ou sacaria')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2922','Lançamento efetuado a título de simples faturamento decorrente de compra para recebimento futuro')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2923','Entrada de mercadoria recebida do vendedor remetente, em venda à ordem')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2924','Entrada para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2925','Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2931','Lançamento efetuado pelo tomador do serviço de transporte quando a responsabilidade de retenção do imposto for atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na Unidade da Federação onde iniciado o serviço')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2932','Aquisição de serviço de transporte iniciado em Unidade da Federação diversa daquela onde inscrito o prestador')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2933','Aquisição de serviço tributado pelo ISSQN')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('2949','Outra entrada de mercadoria ou prestação de serviço não especificado')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('3101','Compra para industrialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('3102','Compra para comercialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('3126','Compra para utilização na prestação de serviço')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('3127','Compra para industrialização sob o regime de “drawback”')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('3201','Devolução de venda de produção do estabelecimento')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('3202','Devolução de venda de mercadoria adquirida ou recebida de terceiros')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('3205','Anulação de valor relativo à prestação de serviço de comunicação')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('3206','Anulação de valor relativo à prestação de serviço de transporte')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('3207','Anulação de valor relativo à venda de energia elétrica')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('3211','Devolução de venda de produção do estabelecimento sob o regime de “drawback”')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('3251','Compra de energia elétrica para distribuição ou comercialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('3301','Aquisição de serviço de comunicação para execução de serviço da mesma natureza')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('3351','Aquisição de serviço de transporte para execução de serviço da mesma natureza')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('3352','Aquisição de serviço de transporte por estabelecimento industrial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('3353','Aquisição de serviço de transporte por estabelecimento comercial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('3354','Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('3355','Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('3356','Aquisição de serviço de transporte por estabelecimento de produtor rural')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('3503','Devolução de mercadoria exportada que tenha sido recebida com fim específico de exportação')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('3551','Compra de bem para o ativo imobilizado')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('3553','Devolução de venda de bem do ativo imobilizado')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('3556','Compra de material para uso ou consumo')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('3650','ENTRADAS DE COMBUSTÍVEIS, DERIVADOS OU NÃO DE PETRÓLEO E LUBRIFICANTES')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('3651','Compra de combustível ou lubrificante para industrialização subseqüente')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('3652','Compra de combustível ou lubrificante para comercialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('3653','Compra de combustível ou lubrificante por consumidor ou usuário final')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('3930','Lançamento efetuado a título de entrada de bem sob amparo de regime especial aduaneiro de admissão temporária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('3949','Outra entrada de mercadoria ou prestação de serviço não especificado')

INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5101','Venda de produção do estabelecimento')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5102','Venda de mercadoria adquirida ou recebida de terceiros')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5103','Venda de produção do estabelecimento, efetuada fora do estabelecimento')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5104','Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5105','Venda de produção do estabelecimento que não deva por ele transitar')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5106','Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5109','Venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5110','Venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5111','Venda de produção do estabelecimento remetida anteriormente em consignação industrial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5112','Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação industrial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5113','Venda de produção do estabelecimento remetida anteriormente em consignação mercantil')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5114','Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5115','Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5116','Venda de produção do estabelecimento originada de encomenda para entrega futura')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5117','Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5118','Venda de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5119','Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5120','Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5122','Venda de produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5123','Venda de mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5124','Industrialização efetuada para outra empresa')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5125','Industrialização efetuada para outra empresa quando a mercadoria recebida para utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5151','Transferência de produção do estabelecimento')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5152','Transferência de mercadoria adquirida ou recebida de terceiros')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5153','Transferência de energia elétrica')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5155','Transferência de produção do estabelecimento, que não deva por ele transitar')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5156','Transferência de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5201','Devolução de compra para industrialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5202','Devolução de compra para comercialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5205','Anulação de valor relativo a aquisição de serviço de comunicação')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5206','Anulação de valor relativo a aquisição de serviço de transporte')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5207','Anulação de valor relativo à compra de energia elétrica')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5208','Devolução de mercadoria recebida em transferência para industrialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5209','Devolução de mercadoria recebida em transferência para comercialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5210','Devolução de compra para utilização na prestação de serviço')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5251','Venda de energia elétrica para distribuição ou comercialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5252','Venda de energia elétrica para estabelecimento industrial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5253','Venda de energia elétrica para estabelecimento comercial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5254','Venda de energia elétrica para estabelecimento prestador de serviço de transporte')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5255','Venda de energia elétrica para estabelecimento prestador de serviço de comunicação')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5256','Venda de energia elétrica para estabelecimento de produtor rural')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5257','Venda de energia elétrica para consumo por demanda contratada')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5258','Venda de energia elétrica a não contribuinte')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5301','Prestação de serviço de comunicação para execução de serviço da mesma natureza')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5302','Prestação de serviço de comunicação a estabelecimento industrial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5303','Prestação de serviço de comunicação a estabelecimento comercial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5304','Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5305','Prestação de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5306','Prestação de serviço de comunicação a estabelecimento de produtor rural')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5307','Prestação de serviço de comunicação a não contribuinte')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5351','Prestação de serviço de transporte para execução de serviço da mesma natureza')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5352','Prestação de serviço de transporte a estabelecimento industrial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5353','Prestação de serviço de transporte a estabelecimento comercial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5354','Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5355','Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5356','Prestação de serviço de transporte a estabelecimento de produtor rural')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5357','Prestação de serviço de transporte a não contribuinte')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5359','Prestação de serviço de transporte a contribuinte ou a não contribuinte quando a mercadoria transportada está dispensada de emissão de nota fiscal')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5401','Venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5402','Venda de produção do estabelecimento de produto sujeito ao regime de substituição tributária, em operação entre contribuintes substitutos do mesmo produto')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5403','Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituto')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5405','Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituído')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5408','Transferência de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5409','Transferência de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5410','Devolução de compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5411','Devolução de compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5412','Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5413','Devolução de mercadoria destinada ao uso ou consumo, em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5414','Remessa de produção do estabelecimento para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5415','Remessa de mercadoria adquirida ou recebida de terceiros para venda fora do estabelecimento, em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5451','Remessa de animal e de insumo para estabelecimento produtor')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5501','Remessa de produção do estabelecimento, com fim específico de exportação')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5502','Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5503','Devolução de mercadoria recebida com fim específico de exportação')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5551','Venda de bem do ativo imobilizado')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5552','Transferência de bem do ativo imobilizado')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5553','Devolução de compra de bem para o ativo imobilizado')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5554','Remessa de bem do ativo imobilizado para uso fora do estabelecimento')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5555','Devolução de bem do ativo imobilizado de terceiro, recebido para uso no estabelecimento')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5556','Devolução de compra de material de uso ou consumo')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5557','Transferência de material de uso ou consumo')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5601','Transferência de crédito de ICMS acumulado')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5602','Transferência de saldo credor de ICMS para outro estabelecimento da mesma empresa, destinado à compensação de saldo devedor de ICMS')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5603','Ressarcimento de ICMS retido por substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5605','Transferência de saldo devedor de ICMS de outro estabelecimento da mesma empresa')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5650','SAÍDAS DE COMBUSTÍVEIS, DERIVADOS OU NÃO DE PETRÓLEO E LUBRIFICANTES')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5651','Venda de combustível ou lubrificante de produção do estabelecimento destinado à industrialização subseqüente')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5652','Venda de combustível ou lubrificante de produção do estabelecimento destinado à comercialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5653','Venda de combustível ou lubrificante de produção do estabelecimento destinado a consumidor ou usuário final')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5654','Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado à industrialização subseqüente')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5655','Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado à comercialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5656','Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado a consumidor ou usuário final')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5657','Remessa de combustível ou lubrificante adquirido ou recebido de terceiros para venda fora do estabelecimento')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5658','Transferência de combustível ou lubrificante de produção do estabelecimento')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5659','Transferência de combustível ou lubrificante adquirido ou recebido de terceiro')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5660','Devolução de compra de combustível ou lubrificante adquirido para industrialização subseqüente')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5661','Devolução de compra de combustível ou lubrificante adquirido para comercializaçã')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5662','Devolução de compra de combustível ou lubrificante adquirido por consumidor ou usuário final')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5663','Remessa para armazenagem de combustível ou lubrificante')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5664','Retorno de combustível ou lubrificante recebido para armazenagem')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5665','Retorno simbólico de combustível ou lubrificante recebido para armazenagem')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5666','Remessa por conta e ordem de terceiros de combustível ou lubrificante recebido para armazenagem')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5901','Remessa para industrialização por encomenda')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5902','Retorno de mercadoria utilizada na industrialização por encomenda')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5903','Retorno de mercadoria recebida para industrialização e não aplicada no referido processo')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5904','Remessa para venda fora do estabelecimento')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5905','Remessa para depósito fechado ou armazém geral')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5906','Retorno de mercadoria depositada em depósito fechado ou armazém geral')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5907','Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5908','Remessa de bem por conta de contrato de comodato')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5909','Retorno de bem recebido por conta de contrato de comodato')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5910','Remessa em bonificação, doação ou brinde')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5911','Remessa de amostra grátis')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5912','Remessa de mercadoria ou bem para demonstração')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5913','Retorno de mercadoria ou bem recebido para demonstração')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5914','Remessa de mercadoria ou bem para exposição ou feira')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5915','Remessa de mercadoria ou bem para conserto ou reparo')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5916','Retorno de mercadoria ou bem recebido para conserto ou reparo')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5917','Remessa de mercadoria em consignação mercantil ou industrial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5918','Devolução de mercadoria recebida em consignação mercantil ou industrial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5919','Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5920','Remessa de vasilhame ou sacaria')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5921','Devolução de vasilhame ou sacaria')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5922','Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5923','Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5924','Remessa para industrialização por conta e ordem do adquirente da mercadoria,')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5925','Retorno de mercadoria recebida para industrialização por conta e ordem do adquirente da mercadoria, quando aquela não transitar pelo estabelecimento do adquirente')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5926','Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5927','Lançamento efetuado a título de baixa de estoque decorrente de perda, roubo ou deterioração')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5928','Lançamento efetuado a título de baixa de estoque decorrente do encerramento da atividade da empresa')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5929','Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também registrada em equipamento Emissor de Cupom Fiscal')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5931','Lançamento efetuado em decorrência da responsabilidade de retenção do imposto por substituição tributária, atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na unidade da Federação onde iniciado o serviço')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5932','Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5933','Prestação de serviço tributado pelo ISSQN')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('5949','Outra saída de mercadoria ou prestação de serviço não especificado')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6101','Venda de produção do estabelecimento')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6102','Venda de mercadoria adquirida ou recebida de terceiros')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6103','Venda de produção do estabelecimento, efetuada fora do estabelecimento')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6104','Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6105','Venda de produção do estabelecimento que não deva por ele transitar')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6106','Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6107','Venda de produção do estabelecimento, destinada a não contribuinte')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6108','Venda de mercadoria adquirida ou recebida de terceiros, destinada a não contribuinte')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6109','Venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6110','Venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6111','Venda de produção do estabelecimento remetida anteriormente em consignação industrial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6112','Venda de mercadoria adquirida ou recebida de Terceiros remetida anteriormente em consignação industrial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6113','Venda de produção do estabelecimento remetida anteriormente em consignação mercantil')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6114','Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6115','Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6116','Venda de produção do estabelecimento originada de encomenda para entrega futura')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6117','Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6118','Venda de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6119','Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6120','Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6122','Venda de produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6123','Venda de mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6124','Industrialização efetuada para outra empresa')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6125','Industrialização efetuada para outra empresa quando a mercadoria recebida para utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6151','Transferência de produção do estabelecimento')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6152','Transferência de mercadoria adquirida ou recebida de terceiros')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6153','Transferência de energia elétrica')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6155','Transferência de produção do estabelecimento, que não deva por ele transitar')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6156','Transferência de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6201','Devolução de compra para industrialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6202','Devolução de compra para comercialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6205','Anulação de valor relativo a aquisição de serviço de comunicação')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6206','Anulação de valor relativo a aquisição de serviço de transporte')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6207','Anulação de valor relativo à compra de energia elétrica')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6208','Devolução de mercadoria recebida em transferência para industrialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6209','Devolução de mercadoria recebida em transferência para comercialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6210','Devolução de compra para utilização na prestação de serviço')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6251','Venda de energia elétrica para distribuição ou comercialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6252','Venda de energia elétrica para estabelecimento industrial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6253','Venda de energia elétrica para estabelecimento comercial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6254','Venda de energia elétrica para estabelecimento prestador de serviço de transporte')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6255','Venda de energia elétrica para estabelecimento prestador de serviço de comunicação')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6256','Venda de energia elétrica para estabelecimento de produtor rural')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6257','Venda de energia elétrica para consumo por demanda contratada')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6258','Venda de energia elétrica a não contribuinte')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6301','Prestação de serviço de comunicação para execução de serviço da mesma natureza')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6302','Prestação de serviço de comunicação a estabelecimento industrial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6303','Prestação de serviço de comunicação a estabelecimento comercial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6304','Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6305','Prestação de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6306','Prestação de serviço de comunicação a estabelecimento de produtor rural')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6307','Prestação de serviço de comunicação a não contribuinte')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6351','Prestação de serviço de transporte para execução de serviço da mesma natureza')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6352','Prestação de serviço de transporte a estabelecimento industrial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6353','Prestação de serviço de transporte a estabelecimento comercial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6354','Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6355','Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6356','Prestação de serviço de transporte a estabelecimento de produtor rural')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6357','Prestação de serviço de transporte a não contribuinte')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6359','Prestação de serviço de transporte a contribuinte ou a não contribuinte quando a mercadoria transportada está dispensada de emissão de nota fiscal')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6401','Venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6402','Venda de produção do estabelecimento de produto sujeito ao regime de substituição tributária, em operação entre contribuintes substitutos do mesmo produto')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6403','Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituto')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6404','Venda de mercadoria sujeita ao regime de substituição tributária, cujo imposto já tenha sido retido anteriormente')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6408','Transferência de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6409','Transferência de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6410','Devolução de compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6411','Devolução de compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6412','Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6413','Devolução de mercadoria destinada ao uso ou consumo, em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6414','Remessa de produção do estabelecimento para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6415','Remessa de mercadoria adquirida ou recebida de terceiros para venda fora do estabelecimento, em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6501','Remessa de produção do estabelecimento, com fim específico de exportação')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6502','Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6503','Devolução de mercadoria recebida com fim específico de exportação')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6551','Venda de bem do ativo imobilizado')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6552','Transferência de bem do ativo imobilizado')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6553','Devolução de compra de bem para o ativo imobilizado')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6554','Remessa de bem do ativo imobilizado para uso fora do estabelecimento')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6555','Devolução de bem do ativo imobilizado de terceiro, recebido para uso no estabelecimento')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6556','Devolução de compra de material de uso ou consumo')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6557','Transferência de material de uso ou consumo')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6603','Ressarcimento de ICMS retido por substituição tributária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6650','SAÍDAS DE COMBUSTÍVEIS, DERIVADOS OU NÃO DE PETRÓLEO E LUBRIFICANTES')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6651','Venda de combustível ou lubrificante de produção do estabelecimento destinado à industrialização subseqüente')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6652','Venda de combustível ou lubrificante de produção do estabelecimento destinado à comercialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6653','Venda de combustível ou lubrificante de produção do estabelecimento destinado a consumidor ou usuário final')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6654','Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado à industrialização subseqüente')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6655','Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado à comercialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6656','Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado a consumidor ou usuário final')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6657','Remessa de combustível ou lubrificante adquirido ou recebido de terceiros para venda fora do estabelecimento')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6658','Transferência de combustível ou lubrificante de produção do estabelecimento')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6659','Transferência de combustível ou lubrificante adquirido ou recebido de terceiro')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6660','Devolução de compra de combustível ou lubrificante adquirido para industrialização subseqüente')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6661','Devolução de compra de combustível ou lubrificante adquirido para comercialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6662','Devolução de compra de combustível ou lubrificante adquirido por consumidor ou usuário final')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6663','Remessa para armazenagem de combustível ou lubrificante')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6664','Retorno de combustível ou lubrificante recebido para armazenagem')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6665','Retorno simbólico de combustível ou lubrificante recebido para armazenagem')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6666','Remessa por conta e ordem de terceiros de combustível ou lubrificante recebido para armazenagem')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6901','Remessa para industrialização por encomenda')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6902','Retorno de mercadoria utilizada na industrialização por encomenda')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6903','Retorno de mercadoria recebida para industrialização e não aplicada no referido processo')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6904','Remessa para venda fora do estabelecimento')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6905','Remessa para depósito fechado ou armazém geral')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6906','Retorno de mercadoria depositada em depósito fechado ou armazém geral')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6907','Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6908','Remessa de bem por conta de contrato de comodato')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6909','Retorno de bem recebido por conta de contrato de comodato')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6910','Remessa em bonificação, doação ou brinde')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6911','Remessa de amostra grátis')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6912','Remessa de mercadoria ou bem para demonstração')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6913','Retorno de mercadoria ou bem recebido para demonstração')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6914','Remessa de mercadoria ou bem para exposição ou feira')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6915','Remessa de mercadoria ou bem para conserto ou reparo')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6916','Retorno de mercadoria ou bem recebido para conserto ou reparo')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6917','Remessa de mercadoria em consignação mercantil ou industrial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6918','Devolução de mercadoria recebida em consignação mercantil ou industrial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6919','Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6920','Remessa de vasilhame ou sacaria')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6921','Devolução de vasilhame ou sacaria')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6922','Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6923','Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6924','Remessa para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6925','Retorno de mercadoria recebida para industrialização por conta e ordem do adquirente da mercadoria, quando aquela não transitar pelo estabelecimento do adquirente')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6929','Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também registrada em equipamento Emissor de Cupom Fiscal')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6931','Lançamento efetuado em decorrência da responsabilidade de retenção do imposto por substituição tributária, atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na unidade da Federação onde iniciado o serviço')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6932','Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6933','Prestação de serviço tributado pelo ISSQN')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('6949','Outra saída de mercadoria ou prestação de serviço não especificado')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('7101','Venda de produção do estabelecimento')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('7102','Venda de mercadoria adquirida ou recebida de terceiros')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('7105','Venda de produção do estabelecimento, que não deva por ele transitar')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('7106','Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('7127','Venda de produção do estabelecimento sob o regime de “drawback”')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('7201','Devolução de compra para industrialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('7202','Devolução de compra para comercialização')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('7205','Anulação de valor relativo à aquisição de serviço de comunicação')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('7206','Anulação de valor relativo a aquisição de serviço de transporte')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('7207','Anulação de valor relativo à compra de energia elétrica')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('7210','Devolução de compra para utilização na prestação de serviço')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('7211','Devolução de compras para industrialização sob o regime de drawback”')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('7251','Venda de energia elétrica para o exterior')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('7301','Prestação de serviço de comunicação para execução de serviço da mesma natureza')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('7358','Prestação de serviço de transporte')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('7501','Exportação de mercadorias recebidas com fim específico de exportação')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('7551','Venda de bem do ativo imobilizado')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('7553','Devolução de compra de bem para o ativo imobilizado')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('7556','Devolução de compra de material de uso ou consumo')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('7650','Saídas de Combustíveis, Derivados ou não de Petróleo e Lubrificantes')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('7651','Venda de combustível ou lubrificante de produção do estabelecimento')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('7654','Venda de combustível ou lubrificante adquirido ou recebido de terceiros')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('7930','Lançamento efetuado a título de devolução de bem cuja entrada tenha ocorrido sob amparo de regime especial aduaneiro de admissão temporária')
INSERT INTO CFOPs (CodCFOP, Descricao) VALUES ('7949','Outra saída de mercadoria ou prestação de serviço não especificado')

update CFOPs set Descricao = UPPER(Descricao) collate SQL_Latin1_General_Cp1251_CS_AS
GO

--update CFOPs set Tipo = 0 where CAST(CodCFOP as int) < 5000
update CFOPs set Tipo = 0 where Descricao NOT like 'VENDA%'
GO

--update CFOPs set Tipo = 1 where CAST(CodCFOP as int) > 5000
update CFOPs set Tipo = 1 where Descricao like 'VENDA%'
GO

alter table CFOPs alter column Tipo tinyint not null
go